### ISSUE TITLE
issue about the reset() function in environment.py

### ISSUE THREAD

**Issue by qxwsniff** [lizijian-buaa/my_MEC_program#1]
I wonder about the function reset() in environment.py.
Each reset will append 50 items in the UE[], then with the precoss of training, the UE[] will be different with that in the other epoch.
why we need to set as this format?

**Comment by lizijian-buaa** [comment]
Dear qxwsniff:
I admit this version of code has many bugs!!! And I have almost already fixed all of them.
But due to my work haven't getting published I do not feel comfortable posting the newest version one. 
Thank you! And good luck!

**Comment by lizijian-buaa** [comment]
P.S. IF you are really interested in this project, want to know want I have done so far and what still remain unsolved, do check the graduation project report( Chinese) I have just uploaded.  If you even want to work on this project, which I am very happy to see, send your info to my e-mail lizijian@buaa.edu.cn .

**Comment by yukeaisiben** [comment]
您好，打扰您。我最近在研究计算卸载相关问题，请问有最新版本的代码吗？想学习一下。
